version: "3.8"

services:
  gtfsdb:
    container_name: gtfsdb
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    tty: true
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
