version: "3.8"

services:
  gtfsdb:
    container_name: gtfsdb
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app
    tty: true
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
  service_pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
volumes:
  pgadmin:
